# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael Goldstein
email: email me michael@
description: > # this means to ignore newlines until "baseurl:"
  All content is licensed as 
  <a href="https://creativecommons.org/licenses/by-nd/4.0/legalcode" target="_blank">
  Creative Commons Attribution-NoDerivatives 4.0
  </a>
  unless otherwise stated.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mgold.io" # the base hostname & protocol for your site
enforce_ssl: mgold.io
github_username:  GitHub

# Build settings
markdown: kramdown

gems:
    - jekyll-sitemap
